import Head from 'next/head'
import Image from 'next/image'
import type { GetStaticProps } from 'next'
import { createServerSideHelpers } from '@trpc/react-query/server'
import superjson from 'superjson'
import { appRouter } from '~/server/api/root'
import { db } from '~/server/db'
import { api } from '~/utils/api'
import { PageLayout } from '~/components/layout'

type PageProps = {
  username: string
}

const ProfilePage: React.FC<PageProps> = ({ username }) => {
  const { data } = api.profile.getUserByUsername.useQuery({
    username
  })

  if (!data) return <p>404</p>

  return (
    <>
      <Head>
        <title>{`@${data.username}'s Profile`} | Twine</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <PageLayout>
        <div className="relative h-36 bg-slate-600">
          <Image
            src={data.imageUrl}
            alt={`${data.username ?? 'User'}'s profile picture`}
            width={128}
            height={128}
            className="absolute bottom-0 left-0 -mb-16 ml-4 rounded-full border-4 border-black bg-black"
          />
        </div>
        <div className="h-16"></div>
        <div className="border-b border-slate-400 p-4 text-2xl font-bold">{`@${data.username}`}</div>
      </PageLayout>
    </>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const helpers = createServerSideHelpers({
    router: appRouter,
    ctx: { db, userId: null },
    transformer: superjson // optional - adds superjson serialization
  })

  const slug = context.params?.slug

  if (typeof slug !== 'string') {
    throw new Error('URL slug is not a string')
  }

  const username = slug.replace('@', '')

  await helpers.profile.getUserByUsername.prefetch({ username })

  return {
    props: {
      trpcState: helpers.dehydrate(),
      username
    }
  }
}

export const getStaticPaths = () => {
  return {
    paths: [],
    fallback: 'blocking'
  }
}

export default ProfilePage
