import Head from "next/head";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

// import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h3 className="text-2xl font-bold text-white">Hello World</h3>
          <div className="flex flex-col justify-center text-white">
            <p>
              {user.isSignedIn ? user.user.fullName : "You are not signed in"}
            </p>
            {user.isSignedIn ? <SignOutButton /> : <SignInButton />}
          </div>
        </div>
      </main>
    </>
  );
}
